"""Messages used by application"""

GET_COMMAND_MSG = "Choose command: "
WELCOME_MSG = "Welcome to Simple Notes CLI!"
COMMANDS_MENU_MSG = "Commands: "
BYE_MSG = "Bye!"
INVALID_INPUT_MSG = "Invalid input, try again!"
INVALID_NOTE_ID_MSG = "Invalid Note ID, cannot read the note!"
INPUT_NOTE_ID_MSG = "Note ID: "
INPUT_NOTE_TITLE_MSG = "Title: "
INPUT_NOTE_CONTENT_MSG = "Content: "
NOTE_ADDED_MSG = "The note is added!"
NOTE_EDITED_MSG = "The note is edited!"
NOTE_REMOVED_MSG = "The note is removed!"
INPUT_SEARCH_STR_MSG = "Search (word or phrase): "
INPUT_SEARCH_START_DATE_STR_MSG = "Start date (format yyyy-dd-mm): "
INPUT_SEARCH_END_DATE_STR_MSG = "End date (format yyyy-dd-mm): "
INVALID_DATE_STR_MSG = "Invalid start and/or end date received, cannot continue search..."
NOTES_NOT_FOUND_MSG = "No one note is found for your search query..."
NOTES_FOUND_MSG = "This notes was found:"